### ISSUE TITLE
Is it convenient for you to provide the code of MultiTargeted-2000 attack.

### ISSUE THREAD

**Issue by TianQi-777** [LayneH/self-adaptive-training#3]
Is it convenient for you to provide the code of MultiTargeted-2000 attack? I hope to test your model under this attack.

**Comment by LayneH** [comment]
Hi,

Please refer to the [official implementation](https://github.com/deepmind/interval-bound-propagation/blob/master/interval_bound_propagation/src/attacks.py#L666) of MultiTargeted attack.
