### ISSUE TITLE
About the computation power of "Self-Adaptive Training: beyond Empirical Risk Minimization"

### ISSUE THREAD

**Issue by momo1986** [LayneH/self-adaptive-training#4]
Hello,

Thanks for your sharing and your outstanding contributions for adversarial learning.

I wonder how much computation power is needed to run the default settings, e.g., batch_size=128.

I tried to reproduce your experiment on a server with 2080Ti and memories of 11G, then the server restarted.

Should I make the batch size smaller to reproduce it?

Could you list the corresponding GPU architectures which is able to run it? How many GPU memories are needed.

Thanks & Regards!
Momo

**Comment by LayneH** [comment]
Hi,

Our experiments were conducted on a single 1080Ti GPU which also has 11GB memory.
Besides, the command, `nvidia-smi`, shows that the memory consumption is 10705MiB.

**Comment by momo1986** [comment]
Thanks.

I think this issue can be closed.

Regards!
Momo
