### ISSUE TITLE
How do you let the train_loader could output the index of data?

### ISSUE THREAD

**Issue by zdhNarsil** [LayneH/self-adaptive-training#7]
Like here https://github.com/LayneH/self-adaptive-training/blob/master/main_adv.py#L189
Normal usage of torch CIFAR10 data loader can only output (inputs, targets) pairs. How do you let it also output the index of data?

**Comment by LayneH** [comment]
We override the datasets at [here](https://github.com/LayneH/self-adaptive-training/blob/master/datasets/datasets.py#L34) to get the index.
