### ISSUE TITLE
Error when loading pretrained checkpoint.

### ISSUE THREAD

**Issue by kevinbro96** [LayneH/self-adaptive-training#8]
I use your code models/wideresnet.py to load the given checkpoint model-wideres-epoch78.pth. But it raised the error:

untimeError: Error(s) in loading state_dict for DataParallel:                                                                                                                                                          Unexpected key(s) in state_dict: "module.sub_block1.layer.0.bn1.weight", "module.sub_block1.layer.0.bn1.bias", "module.sub_block1.layer.0.bn1.running_mean", "module.sub_block1.layer.0.bn1.running_var", "module.sub_block1.layer.0.bn1.num_batches_tracked", "module.sub_block1.layer.0.conv1.weight", "module.sub_block1.layer.0.bn2.weight", "module.sub_block1.layer.0.bn2.bias", "module.sub_block1.layer.0.bn2.running_mean", "module.sub_block1.layer.0.bn2.running_var", "module.sub_block1.layer.0.bn2.num_batches_tracked", "module.sub_block1.layer.0.conv2.weight", "module.sub_block1.layer.0.convShortcut.weight", "modul
e.sub_block1.layer.1.bn1.weight", "module.sub_block1.layer.1.bn1.bias", "module.sub_block1.layer.1.bn1.running_mean", "module.sub_block1.layer.1.bn1.running_var", "module.sub_block1.layer.1.bn1.num_batches_tr
acked", "module.sub_block1.layer.1.conv1.weight", "module.sub_block1.layer.1.bn2.weight", "module.sub_block1.layer.1.bn2.bias", "module.sub_block1.layer.1.bn2.running_mean", "module.sub_block1.layer.1.bn2.run
ning_var", "module.sub_block1.layer.1.bn2.num_batches_tracked", "module.sub_block1.layer.1.conv2.weight", "module.sub_block1.layer.2.bn1.weight", "module.sub_block1.layer.2.bn1.bias", "module.sub_block1.layer
.2.bn1.running_mean", "module.sub_block1.layer.2.bn1.running_var", "module.sub_block1.layer.2.bn1.num_batches_tracked", "module.sub_block1.layer.2.conv1.weight", "module.sub_block1.layer.2.bn2.weight", "modul
e.sub_block1.layer.2.bn2.bias", "module.sub_block1.layer.2.bn2.running_mean", "module.sub_block1.layer.2.bn2.running_var", "module.sub_block1.layer.2.bn2.num_batches_tracked", "module.sub_block1.layer.2.conv2
.weight", "module.sub_block1.layer.3.bn1.weight", "module.sub_block1.layer.3.bn1.bias", "module.sub_block1.layer.3.bn1.running_mean", "module.sub_block1.layer.3.bn1.running_var", "module.sub_block1.layer.3.bn
1.num_batches_tracked", "module.sub_block1.layer.3.conv1.weight", "module.sub_block1.layer.3.bn2.weight", "module.sub_block1.layer.3.bn2.bias", "module.sub_block1.layer.3.bn2.running_mean", "module.sub_block1
.layer.3.bn2.running_var", "module.sub_block1.layer.3.bn2.num_batches_tracked", "module.sub_block1.layer.3.conv2.weight", "module.sub_block1.layer.4.bn1.weight"

**Comment by kevinbro96** [comment]
What is sub_block1?

**Comment by LayneH** [comment]
Hi,

Thank you for pointing out the issue.

We initially used the model definition given by TRADES, which defines an unused sub_block1 in [here](https://github.com/yaodongyu/TRADES/blob/master/models/wideresnet.py#L63). 
We removed this block from our code at the time of release but forgot to clean the checkpoint.
You can now download the clean checkpoint from [this url](https://drive.google.com/file/d/1yX9kVmqxImGQAckSOtlAImarRnZ30nMt/view?usp=sharing).
